<?php


namespace common\base;

use yii\web\Controller;
use yii\web\HttpException;

class BaseConsoleController extends \yii\console\Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action);
    }
    public function afterAction($action, $result)
    {

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}