<?php


namespace frontend\controllers;


use common\base\BaseController;
use frontend\controllers\actions\report\AddCommentAction;
use frontend\controllers\actions\report\AddReportAction;
use frontend\controllers\actions\report\ChangeReportStatusAction;
use frontend\controllers\actions\report\CheckReportsAction;
use frontend\controllers\actions\report\GetNewCommentsAction;
use frontend\controllers\actions\report\SkipReportAction;

class ReportController extends BaseController {
    public $layout = 'base';


    public function actions() {

        return [
            'check-reports' => ['class' => CheckReportsAction::class],
            'change-report-status' => ['class' => ChangeReportStatusAction::class],
            'add-report' => ['class' => AddReportAction::class],
            'add-comment' => ['class' => AddCommentAction::class],
            'get-new-comments' => ['class' => GetNewCommentsAction::class],
        ];

    }

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}