<?php


namespace app\controllers;


use app\base\BaseController;
use app\controllers\actions\report\ChangeReportStatusAction;
use app\controllers\actions\report\CheckReportsAction;
use app\controllers\actions\report\SkipReportAction;

class ReportController extends BaseController {
    public $layout = 'base';


    public function actions() {

        return [
            'check-reports' => ['class' => CheckReportsAction::class],
            'change-report-status' => ['class' => ChangeReportStatusAction::class],
        ];

    }

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}