<?php


namespace app\controllers;


use app\base\BaseController;
use app\controllers\actions\site\ErrorAction;
use app\controllers\actions\task\CreateAction;
use app\controllers\actions\task\DeleteAction;
use app\controllers\actions\task\FinishAction;
use app\controllers\actions\task\TransferAction;
use app\controllers\actions\task\UpdateAllAction;
use app\controllers\actions\task\ViewAction;
use app\controllers\actions\task\ViewAllTasks;


class TaskController extends BaseController {

    public $layout = 'base';


    public function actions() {

        return [
            'create'=>['class'=>CreateAction::class, 'view' => 'create'],
            'change' => ['class' =>CreateAction::class, 'view' => 'create'],
            'transfer'=>['class'=>TransferAction::class],
            'view' => ['class' =>ViewAction::class],
            'report' => ['class' =>ViewAllTasks::class],
            'del' => ['class' =>DeleteAction::class],
            'restore' => ['class' =>DeleteAction::class],
            'hard-del' => ['class' =>DeleteAction::class],
            'finish' => ['class' =>FinishAction::class],
            'update-all' => ['class' =>UpdateAllAction::class],
            'error' => ['class' => ErrorAction::class],
        ];

    }

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}