<?php


namespace app\controllers;

use app\base\BaseController;
use app\controllers\actions\site\ErrorAction;
use app\controllers\actions\user\ConfirmationCuratorsEmailAction;
use app\controllers\actions\user\CuratorsEmailConfirmAction;
use app\controllers\actions\user\MentorAction;
use app\controllers\actions\user\StatisticsAction;
use app\controllers\actions\user\UpdateAction;
use app\controllers\actions\user\ViewAction;

class UserController extends BaseController {
    public $layout = 'base';

    public function actions() {

        return [
            'view'=>['class'=>ViewAction::class],
            'update' => ['class' =>UpdateAction::class],
            'error' => ['class' => ErrorAction::class],
            'curators-email-confirm' => ['class' => CuratorsEmailConfirmAction::class],
            'confirmation-curators-email' => ['class' => ConfirmationCuratorsEmailAction::class],
            'mentor' => ['class' => MentorAction::class],
            'statistics' => ['class' => StatisticsAction::class],
        ];

    }

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}