<?php


namespace app\controllers;

use app\base\BaseController;
use app\controllers\actions\user\UpdateAction;
use app\controllers\actions\user\ViewAction;

class UserController extends BaseController {
    public $layout = 'base';

    public function actions() {

        return [
            'view'=>['class'=>ViewAction::class],
            'update' => ['class' =>UpdateAction::class],
        ];

    }

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}