<?php


namespace app\components;


use app\base\BaseComponent;
use app\models\ReportComments;
use app\models\UsersReports;
use yii\web\UploadedFile;

class ReportCommentsComponent extends BaseComponent {
    public $modelClass;

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getModel() {
        return new $this->modelClass;
    }

    /**
     * @param $reportId
     * @return UsersReports|array|\yii\db\ActiveRecord|null
     */
    public function getReportCommentsByReportID($reportId) {
//        $todayUTC = date('Y-m-d');
        $comments = ReportComments::find()
            ->where([
                'report_id' => $reportId,
            ])
            ->joinWith('user')
//            ->joinWith('comments_to_users')
//            ->where(['users.id' => 2])
//            ->andWhere(['OR',
//                ['IS', 'status', null],
//                ['<', 'status', 4],
//            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->limit(10)
            ->all();
        return $comments;
    }

    public function getNewComments() {
        $user_id = \Yii::$app->user->getId();

        $comments = ReportComments::find()
            ->where([
                'viewed' => null,
            ])
            ->andWhere(['not', ['`report_comments`.user_id' => $user_id]])
            ->joinWith('report')
            ->where(['`users_reports`.user_id' => $user_id])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        return $comments;
    }

    public function addReportComment(ReportComments $comment) {
        $userId = \Yii::$app->user->getId();

        $comment->uploadFiles = UploadedFile::getInstancesByName('ReportComments[uploadFiles]');
        $fileSaver = \Yii::createObject(['class' => FileSaverComponent::class]);
        $comment->user_id = $userId;
        $fileArr = [];
        if ($comment->uploadFiles) {
            $comment->comment = $comment->comment ? $comment->comment : 'yii2_null';
        }
        if ($comment->validate()) {
            if ($comment->uploadFiles) {
                $comment->comment = $comment->comment === 'yii2_null' ? ' ' : $comment->comment;
                foreach ($comment->uploadFiles as $file) {
                    $file = $fileSaver->saveReportFile($file, $userId);
                    array_push($fileArr, $file);
                    if (!$file) {
                        return false;
                    }
                }
                $comment->files = join('/', $fileArr);
            } else {
                $comment->files = null;
            }

            if ($comment->save(false)) {
                return $comment;
            }
            \Yii::error($comment->getErrors());
            return false;
        }
        //валидация файлов не прошла
        return false;
    }

    public function updateViews($comments):bool {
        foreach ($comments as $comment) {
            if ($comment->user_id != \Yii::$app->user->getId() && $comment->viewed != 1) {
                $comment->viewed = 1;
                $comment->save(false);
            }
        }
        return true;
    }

}