<?php


namespace app\components;


use app\base\BaseComponent;
use app\models\Tasks;
use app\models\User;
use app\models\UsersReports;
use phpDocumentor\Reflection\Types\False_;
use yii\db\ActiveRecord;
use yii\db\conditions\BetweenCondition;
use yii\helpers\Console;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

class TasksComponent extends BaseComponent {
    public $modelClass;
    // список праздников
    public $holidays = [
            '01.01.2021',
            '04.01.2021',
            '05.01.2021',
            '06.01.2021',
            '07.01.2021',
            '08.01.2021',
            '22.02.2021',
            '23.02.2021',
            '08.03.2021',
            '03.05.2021',
            '10.05.2021',
            '14.06.2021',
            '04.11.2021',
            '31.12.2021',
        ];

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getModel() {
        return new $this->modelClass;
    }

    public function getUserTask($id) {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'id' => $id,
            ])
            ->one();
        return $tasks;
    }

    public function getUserTasks() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 1,
                'deleted' => 0,
                'finished' => 0,
            ])
            ->orderBy(['date_create' => SORT_DESC])
            ->all();
        return $tasks;
    }

    // возвращает задачи на сегодня, с планируемым завершением до конца дня
    public function getTodayUserTasks() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 1,
                'deleted' => 0,
//                'repeat_created' => null,
//                'finished' => 0,
            ])
            ->andWhere(['AND',
                ['>=', 'date_calculate', (new \DateTime(date(date('d.m.Y'))))->format('Y-m-d H:i:s')],
                ['<=', 'date_calculate', (new \DateTime(date('d.m.Y') . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->andWhere(['AND',
//                ['>=', 'date_start', (new \DateTime(date('d.m.Y')  . ' 00:00:00'))->format('Y-m-d H:i:s')],
                ['<=', 'date_start', (new \DateTime(date('d.m.Y') . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        return $tasks;
    }
    // возвращает задачи на завтра
    public function getTomorrowUserTasks() {
        $nextDay = strtotime("+1 day");
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 1,
                'deleted' => 0,
//                'repeat_created' => null,
//                'finished' => 0,
            ])
            ->andWhere(['AND',
                ['>=', 'date_calculate', (new \DateTime(date(date('d.m.Y', $nextDay))))->format('Y-m-d H:i:s')],
                ['<=', 'date_calculate', (new \DateTime(date('d.m.Y', $nextDay) . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->andWhere(['AND',
//                ['>=', 'date_start', (new \DateTime(date('d.m.Y', $nextDay)  . ' 00:00:00'))->format('Y-m-d H:i:s')],
                ['<=', 'date_start', (new \DateTime(date('d.M.Y', $nextDay) . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        return $tasks;
    }

    // возвращает задачи на месяц на текущий момент
    public function getTodayUserAims() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 2,
                'deleted' => 0,
//                'finished' => 0,
            ])
//            ->andWhere(['AND',
//                ['>=', 'date_calculate', (new \DateTime(date('01.'.date('m.Y'))))->format('Y-m-d H:i:s')],
//                ['<=', 'date_calculate', (new \DateTime(date('t', time()).date('.m.Y') . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
//            ->andWhere(['AND',
////                ['>=', 'date_start', (new \DateTime(date('01.'.date('m.Y'))))->format('Y-m-d H:i:s')],
//                ['<=', 'date_start', (new \DateTime(date('t', time()).date('.m.Y') . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        return $tasks;
    }

    // возвращает задачи на год на текущий момент
    public function getTodayUserGoals() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 3,
                'deleted' => 0,
//                'finished' => 0,
            ])
//            ->andWhere(['AND',
//                ['>=', 'date_calculate', (new \DateTime(date('01.01.'.date('Y'))))->format('Y-m-d H:i:s')],
//                ['<=', 'date_calculate', (new \DateTime(date('31.12.'.date('Y')) . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
//            ->andWhere(['AND',
////                ['>=', 'date_start', (new \DateTime(date('01.01.'.date('Y'))))->format('Y-m-d H:i:s')],
//                ['<=', 'date_start', (new \DateTime(date('31.12.'.date('Y')) . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        return $tasks;
    }

    public function getAllTasksArr() {
        $tasks = Tasks::find()
            ->where(
                [
                    'user_id' => \Yii::$app->user->getId(),
                    'type_id' => 1,
                    'deleted' => 0,
                    'finished' => 0,
                ]
            )
            ->orderBy(['date_start' => SORT_DESC])
            ->all();
        $arr = [];
        foreach ($tasks as $task) {
            $arr += [$task->id => $task->task];
        }
        return $arr;
    }

    public function getAllAimsArr() {
        $tasks = Tasks::find()
            ->where(
                [
                    'user_id' => \Yii::$app->user->getId(),
                    'type_id' => 2,
                    'deleted' => 0,
                    'finished' => 0,
                ]
            )
            ->orderBy(['date_start' => SORT_DESC])
            ->all();
        $arr = [];
        foreach ($tasks as $task) {
            $arr += [$task->id => $task->task];
        }
        return $arr;
    }

    public function getAllGoalsArr() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 3,
                'deleted' => 0,
                'finished' => 0,
            ])
//            ->andWhere(['AND',
//                    ['<=', 'date_calculate', (new \DateTime(date('01.'.date('m.Y'))))->format('Y-m-d')],
//                    ['>=', 'date_calculate', (new \DateTime(date('t', time()).'.'.date('m.Y')))->format('Y-m-d H:i:s')]
//                ])
            ->orderBy(['date_start' => SORT_DESC])
            ->all();
        $arr = [];
        foreach ($tasks as $task) {
            $arr += [$task->id => $task->task];
        }
        return $arr;
    }

    public function getAllUserTasks() {
        return \Yii::$app->dao->getAllUserTasks(\Yii::$app->user->getId());
    }

    public function getChildTasks($taskId, $typeId=null) {
        $targetProp = '';
        if (!$typeId) {
            $task = Tasks::findOne(['id' => $taskId, 'user_id' => \Yii::$app->user->getId()]);
            $typeId = $task->type_id;
        }

        if ($typeId == 3) {
            $targetProp = 'goal_id';
        } elseif ($typeId == 2) {
            $targetProp = 'aim_id';
        }

        $childesFromBD = $this->getChilds($targetProp, $taskId);
        $childTasks = [];

        foreach ($childesFromBD as $child) {
            if ($child->aim_id == null) {
                $childTasks += [$child->id => []];
            } else {
                if (!array_key_exists($child->aim_id, $childTasks)) {
                    $childTasks += [$child->aim_id => [$child->id => []]];

                } else {
                    $childTasks[$child->aim_id] += [$child->id => []];
                }
            }
        }
        return $childTasks;
    }

    private function getChilds($targetProp, $taskId) {
        $childes = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                $targetProp => $taskId,
                'deleted' => 0,
                'finished' => 0,
            ])
            ->orderBy(['date_start' => SORT_DESC])
            ->all();
        return $childes;
    }

    public function getDeletedTasks() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'deleted' => 1,
//                'finished' => 0,
            ])
            ->orderBy(['date_start' => SORT_DESC])
            ->all();
        return $tasks;
    }

    public function addTask(Tasks $task) {
//        $task->filesReal = UploadedFile::getInstances($task, 'filesReal');
//        $fileSaver = \Yii::createObject(['class' => FileSaverComponent::class]);
        if (!$task->user_id) {
            $task->user_id = \Yii::$app->user->getId();
        }

        if ($task->validate()) {
//            foreach ($task->filesReal as &$file) {
//                $file = $fileSaver->saveFile($file);
//                if (!$file) {
//                    return false;
//                }
//            }
//            $task->files = implode('|',$task->filesReal);

            // валидация + сохранение активности
            if ($task->save()) {
                return $task;
            }
            \Yii::error($task->getErrors());
            return false;
        }
        //валидация файлов не прошла
        return false;
    }

    public function deleteTask(Tasks $task) {
        if ($task->validate()) {
            $task->deleted = 1;
            if ($task->save(false)) {
                return true;
            }
            return false;
        }

        return false;
    }

    public function finishTask(Tasks $task) {
        if ($task->validate()) {
            if ($task->finished == 1) {
                $task->finished = 0;
                $task->date_finish = null;
            } else {
                $task->finished = 1;
                $task->date_finish = date('Y-m-d H:i:s');
            }

            if ($task->save(false)) {
                return true;
            }
            return false;
        }

        return false;
    }

    public function restoreTask(Tasks $task) {
        if ($task->validate()) {
            $task->deleted = 0;
            if ($task->save(false)) {
                return true;
            }
            return false;
        }
        return false;
    }

    public function hardDeleteTask(Tasks $task) {
        if ($task->delete()) {
            return true;
        }
//        \Yii::error($task->getErrors());
        return false;
    }

    public function updateAllTasks($tasks) {
        $this->modelClass = Tasks::class;
        foreach ($tasks as $task) {
            if (\Yii::$app instanceof yii\console\Application) {
                $user_id = $task->user_id;
            } else {
                $user_id = \Yii::$app->user->getId();
            }

            $model = $this->getModel();
            $taskToUpdate = $model->findOne(['id' => $task['id'], 'user_id' => $user_id]);
            $taskToUpdate->load(['Tasks' => $task]);
            $this->addTask($taskToUpdate);
        }
        return true;
    }

    public function findTodayNotifTask() {
        return Tasks::find()
            ->andWhere('useNotification = 1')
            ->andWhere('deleted = 0')
            ->andWhere('dateStart>=:date',[':date'=>date('Y-m-d')])
            ->andWhere('dateStart<=:date2',[':date2'=>date('Y-m-d'. ' 23:59:59')])->all();
    }

    private function getDataToRenewTasks($type_id) {
        $prev = '';
        switch ($type_id) {
            case 1:
                $prev = strtotime("-1 day");
                $dateFrom = (new \DateTime(date('d.m.Y', $prev)  . ' 00:00:00'))->format('Y-m-d H:i:s');
                $dateTo = (new \DateTime(date('d.m.Y', $prev) . ' 23:59:59'))->format('Y-m-d H:i:s');
                break;
            case 2:
                $prev = strtotime(date('15.m.Y') . "-1 month");
                $dateFrom = (new \DateTime(date('01.m.Y', $prev)  . ' 00:00:00'))->format('Y-m-d H:i:s');
                $dateTo = (new \DateTime(date('t', $prev).date('.m.Y', $prev) . ' 23:59:59'))->format('Y-m-d H:i:s');
                break;
            case 3:
                $prev = strtotime("-1 year");
                $dateFrom = (new \DateTime(date('01.01.'.date('Y',$prev))))->format('Y-m-d H:i:s');
                $dateTo = (new \DateTime(date('31.12.'.date('Y',$prev)) . ' 23:59:59'))->format('Y-m-d H:i:s');
                break;
        }
        $newDate = (new \DateTime(date('d.m.Y') . ' 23:59:59'))->format('Y-m-d H:i:s');

        return [
            'newDate' => $newDate,
            'dateFrom' => $dateFrom,
            'dateTo' => $dateTo,
        ];
    }

    public function checkDataToRenew($type_id):bool {
        $renewData = $this->getDataToRenewTasks($type_id);
        $check = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'type_id' => $type_id,
                'deleted' => 0,
                'finished' => 0,
            ])->andWhere(['AND',
                ['>=', 'date_calculate', $renewData['dateFrom']],
                ['<=', 'date_calculate', $renewData['dateTo']],
            ])
            ->orderBy(['date_create' => SORT_DESC])
            ->all();

        if ($check) {
            return true;
        } else {
            return false;
        }
    }

    public function renewLastUnfinishedTasks($type_id):bool {
        $renewData = $this->getDataToRenewTasks($type_id);
        $update = Tasks::updateAll(
            ['date_calculate' => $renewData['newDate']],
                ['and',
                    ['user_id' => \Yii::$app->user->getId()],
                    ['type_id' => $type_id],
                    ['deleted' => 0],
                    ['finished' => 0],
                    ['>=', 'date_calculate', $renewData['dateFrom']],
                    ['<=', 'date_calculate', $renewData['dateTo']],
//                    ['>=', 'date_start', (new \DateTime(date('d.m.Y', $prev)  . ' 00:00:00'))->format('Y-m-d H:i:s')],
//                    ['<=', 'date_start', (new \DateTime(date('d.M.Y', $prev) . ' 23:59:59'))->format('Y-m-d H:i:s')],
                ]
        );
        if ($update) {
            return true;
        }
        return false;
    }

    public function getWidgetData($type_id, $nextPeriod) {
        if ($nextPeriod == 0) {
            switch ($type_id) {
                case 3:
                    $title = 'Цели на год';
                    $tasks = $this->getTodayUserGoals();
                    break;
                case 2:
                    $month = \Yii::$app->params['monthsImenit'][\Yii::$app->formatter->asDate(date('Y-m-d'), 'M')];
                    $title = 'Задачи на '. $month;
                    $tasks = $this->getTodayUserAims();
                    break;
                case 1:
                    $title = 'Что я сделал сегодня';
                    $tasks = $this->getTodayUserTasks();
                    break;
            }
        } else {
            $title = 'Что я сделаю завтра';
            $tasks = $this->getTomorrowUserTasks();
        }

        return [
            'title' => $title,
            'tasks' => $tasks,
            'nextPeriod' => $nextPeriod,
        ];
    }

    private function existRepeatTaskInArr($task, $searchArr) {
        $keysArr = [];
        foreach ($searchArr as $key => $searchTask) {
            if ($searchTask['repeated_by_id'] == $task['id']) {
                array_push($keysArr, $key);
            }
        }
        return $keysArr;
    }

    public function createRepeatedTasks():bool {
        $this->modelClass = Tasks::class;
        $today = date('d.m.Y');
//        $today = date('23.02.2021');
        $tomorrow = date('d.m.Y', strtotime($today. ' +1 day'));
        $tasksToRepeat = Tasks::find()
            ->where([
//                'user_id' => \Yii::$app->user->getId(),
                'type_id' => 1,
                'deleted' => 0,
            ])
            ->andWhere(['not', ['repeat_type_id' => null]])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        $alreadyRepeatedTasks = Tasks::find()
            ->where([
                'repeat_type_id' => null,
            ])
            ->andWhere(['not', ['repeated_by_id' => null]])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();

        $tasksToCreateToday = [];
        $tasksToCreateNextPeriod = [];
        foreach ($tasksToRepeat as $task) {
            if ($task->repeat_start) {
                $dateStart = $task->repeat_start;
            } else {
                $dateStart = date('Y-m-d', strtotime($task->date_create));
            }
            $dateEnd = $task->repeat_end ? $task->repeat_end : '2100-01-01';

            $dateStartTask = \Yii::$app->formatter->asDateTime(
                $task->date_start, 'php:d.m.Y'
            );
            $dateCalcTask = \Yii::$app->formatter->asDateTime(
                $task->date_calculate, 'php:d.m.Y'
            );

            // ищем ранее созданные повторные такие же задачи
            $findRepeatedTasksKeys = $this->existRepeatTaskInArr($task, $alreadyRepeatedTasks);
            switch ($task->repeat_type_id) {
                case 1:
                    if ($findRepeatedTasksKeys) {
                        $todayAdd = true;
                        $tomorrowAdd = true;
                        foreach ($findRepeatedTasksKeys as $key) {
                            // проверяем даты старта и расчетные завершения задач и если для текущего периода не создавались задачи, то добавляем задачу в массив $tasksToCreate для последующего создания задачи
                            $dateStartRepeated = \Yii::$app->formatter->asDateTime(
                                $alreadyRepeatedTasks[$key]->date_start, 'php:d.m.Y'
                            );
                            $dateCalcRepeated = \Yii::$app->formatter->asDateTime(
                                $alreadyRepeatedTasks[$key]->date_calculate, 'php:d.m.Y'
                            );
                            if ($dateStartRepeated == $today || $dateStartTask == $today) {
                                $todayAdd = false;
                            }
                            if ($dateStartRepeated == $tomorrow  || $dateStartTask == $tomorrow) {
                                $tomorrowAdd = false;
                            }
                        }

                        if ($todayAdd && strtotime($today) >= strtotime($dateStart) && strtotime($today) < strtotime($dateEnd)) {
                            array_push($tasksToCreateToday, $task);
                        }
                        if ($tomorrowAdd && strtotime($tomorrow) >= strtotime($dateStart) && strtotime($tomorrow) < strtotime($dateEnd)) {
                            array_push($tasksToCreateNextPeriod, $task);
                        }

                    } else {

                        if ($dateStartTask != $today && $dateCalcTask != $today && strtotime($today) >= strtotime($dateStart) && strtotime($today) < strtotime($dateEnd)) {
                            array_push($tasksToCreateToday, $task);
                        }
                        if ($dateStartTask != $tomorrow && $dateCalcTask != $tomorrow && strtotime($tomorrow) >= strtotime($dateStart) && strtotime($tomorrow) < strtotime($dateEnd)) {
                            array_push($tasksToCreateNextPeriod, $task);
                        }
                    }
                    break;
                case 2:
                    $nextRepeatDate = $this->getNextRepeatDatePlusMonth($task->date_create, $dateStart);

                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks)) {
                       array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 3:
                    $nextRepeatDate = $this->getNextRepeatDatePlusYear($task->date_create,  $dateStart);

                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks)) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 4:
                    $nextRepeatDate = $this->getNextRepeatDatePlusQuarter($task->date_create,  $dateStart);

                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks)) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 5:
                    $nextRepeatDate = $this->getNextRepeatDatePlusWeek($task->date_create,  $dateStart);
                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks)) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 6:
                    $nextRepeatDate = date('d.m.Y', $this->getNextWorkday(true));
                    if ($today == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($today, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $today && $dateCalcTask != $today) {
                        array_push($tasksToCreateToday, $task);
                    }

                    $nextRepeatDate = date('d.m.Y', $this->getNextWorkday($dateStart));
                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $tomorrow && $dateCalcTask != $tomorrow) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 7:
                    $nextRepeatDate = date('d.m.Y', $this->getNextHoliday($dateStart));
                    if ($today == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($today, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $today && $dateCalcTask != $today) {
                        array_push($tasksToCreateToday, $task);
                    }

                    $nextRepeatDate = date('d.m.Y', $this->getNextHoliday($dateStart));
                    if ($tomorrow == $nextRepeatDate && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $tomorrow && $dateCalcTask != $tomorrow) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
                case 8:
                    // получаем массив повторов по дням недели из базы
                    $selectedRepeats = explode(',', $task->repeated_weekdays);
                    for ($i = 0; $i < count($selectedRepeats); $i++) {
                        $selectedRepeats[$i] = $selectedRepeats[$i] == 7 ? 0 : $selectedRepeats[$i];
                    }

                    $todayAdd = false;
                    $dayNum = (int) date('w');
                    if (in_array($dayNum, $selectedRepeats)) {
                        $todayAdd = true;
                    }

                    if ($todayAdd && $this->checkRepeatedTasksAddedToDate($today, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $today && $dateCalcTask != $today) {
                        array_push($tasksToCreateToday, $task);
                    }

                    $tomorrowAdd = false;
                    $dayNumTomorrow = (int) date('w', strtotime("+1 day"));

                    if (in_array($dayNumTomorrow, $selectedRepeats)) {
                        $tomorrowAdd = true;
                    }
                    if ($tomorrowAdd && $this->checkRepeatedTasksAddedToDate($tomorrow, $findRepeatedTasksKeys, $alreadyRepeatedTasks) && $dateStartTask != $tomorrow && $dateCalcTask != $tomorrow) {
                        array_push($tasksToCreateNextPeriod, $task);
                    }
                    break;
            }
        }

        // создание повторных задач
        foreach ($tasksToCreateToday as $task) {
            $model = $this->getModel();
            $model->user_id = $task->user_id;
            $model->private_id = $task->private_id;
            $model->type_id = $task->type_id;
            $model->cat_id = $task->cat_id;
            $model->aim_id = $task->aim_id;
            $model->goal_id = $task->goal_id;
            $model->task = $task->task;
            $model->main_img = $task->main_img;
//            $model->group_id = $task->group_id;
            $model->hashtags = $task->hashtags;
            $model->deleted = $task->deleted;
            $model->repeat_type_id = null;
            $model->secret_key = $task->secret_key;
            $model->nextPeriod = 0;
            // id основной задачи пишем в repeated_by_id
            $model->repeated_by_id = $task->id;

            $this->addTask($model);
        }
        foreach ($tasksToCreateNextPeriod as $task) {
            $model = $this->getModel();
            $model->user_id = $task->user_id;
            $model->private_id = $task->private_id;
            $model->type_id = $task->type_id;
            $model->cat_id = $task->cat_id;
            $model->aim_id = $task->aim_id;
            $model->goal_id = $task->goal_id;
            $model->task = $task->task;
            $model->main_img = $task->main_img;
//            $model->group_id = $task->group_id;
            $model->hashtags = $task->hashtags;
            $model->deleted = $task->deleted;
            $model->repeat_type_id = null;
            $model->secret_key = $task->secret_key;
            $model->nextPeriod = 1;
            // id основной задачи пишем в repeated_by_id
            $model->repeated_by_id = $task->id;

            $this->addTask($model);
        }
        return true;
    }

    private function getNextWorkday($dateStart, $today=null) {
        // список праздников (нерабочих дней)
        $bankHols = $this->holidays;

        if ($dateStart && strtotime($dateStart) > time()) {
            $nextDays = array(strtotime($dateStart . ' +1 day'), strtotime($dateStart . ' +2 days'), strtotime($dateStart . ' +3 days'), strtotime($dateStart . ' +4 days'), strtotime($dateStart . ' +5 days'), strtotime($dateStart . ' +6 days'), strtotime($dateStart . ' +7 days'));
        } else {
            $nextDays = array(strtotime('+1 day'), strtotime('+2 days'), strtotime('+3 days'), strtotime('+4 days'), strtotime('+5 days'), strtotime('+6 days'), strtotime('+7 days'));
        }

        if ($today) {
            array_unshift($nextDays, strtotime($today));
        }
        for ($i = 0; $i < count($nextDays); $i++) {
            $dayNum = (int) date('w', $nextDays[$i]);
            $daytext = date('d.m.Y', $nextDays[$i]);
            if (($dayNum > 0) && ($dayNum < 6) && (!in_array($daytext, $bankHols))) {
              return $nextDays[$i];
            }
        }
        return false;
    }

    private function getNextHoliday($dateStart, $today=null) {
        // список праздников (нерабочих дней)
        $bankHols = $this->holidays;

        if ($dateStart && strtotime($dateStart) > time()) {
            $nextDays = array(strtotime($dateStart . ' +1 day'), strtotime($dateStart . ' +2 days'), strtotime($dateStart . ' +3 days'), strtotime($dateStart . ' +4 days'), strtotime($dateStart . ' +5 days'), strtotime($dateStart . ' +6 days'), strtotime($dateStart . ' +7 days'));
        } else {
            $nextDays = array(strtotime('+1 day'), strtotime('+2 days'), strtotime('+3 days'), strtotime('+4 days'), strtotime('+5 days'), strtotime('+6 days'), strtotime('+7 days'));
        }
        if ($today) {
            array_unshift($nextDays, strtotime($today));
        }
        for ($i = 0; $i < count($nextDays); $i++) {
            $dayNum = (int) date('w', $nextDays[$i]);
            $daytext = date('d.m.Y', $nextDays[$i]);
            if (($dayNum == 0) || ($dayNum == 6) || (in_array($daytext, $bankHols))) {
              return $nextDays[$i];
            }
        }
        return false;
    }

    private function checkRepeatedTasksAddedToDate($date, $findRepeatedTasksKeys, $alreadyRepeatedTasks) {
        $result = true;
        if ($findRepeatedTasksKeys) {
            foreach ($findRepeatedTasksKeys as $key) {
                $dateStartRepeated = \Yii::$app->formatter->asDateTime(
                    $alreadyRepeatedTasks[$key]->date_start, 'php:d.m.Y'
                );
                $dateCalcRepeated = \Yii::$app->formatter->asDateTime(
                    $alreadyRepeatedTasks[$key]->date_calculate, 'php:d.m.Y'
                );
                if ($dateStartRepeated == $date) {
                    $result = false;
                }
            }
        }
        return $result;
    }

    private function getNextRepeatDatePlusMonth($dateCreate, $dateStart, $the_date=null) {
        if (!$the_date) {
            if ($dateStart && strtotime($dateStart) > time()) {
                $the_date = strtotime($dateStart);
            } else {
                $the_date = strtotime($dateCreate);
            }
            $day = date('d', $the_date);
            $month = date('m', strtotime('15' . date('.m.Y', $the_date) . ' +1 month',));
            $year = date('Y', strtotime('+1 month', $the_date));
        } else {
            $day = date('d', $the_date);
            $month = date('m', $the_date);
            $year = date('Y', $the_date);
        }

        if (!checkdate(intval($month), intval($day), intval($year))) {
            $nextRepeatDate = date('d.m.Y', strtotime('last day of next month', $the_date));
        } else {
            $nextRepeatDate = date('d.m.Y', strtotime("+1 month", $the_date));
        }

        if (strtotime($nextRepeatDate) <= time()) {
            $the_date = strtotime($nextRepeatDate);
            return $this->getNextRepeatDatePlusMonth($dateCreate, $dateStart, $the_date);
        }
        return $nextRepeatDate;
    }

    private function getNextRepeatDatePlusYear($dateCreate, $dateStart, $the_date=null) {
        if (!$the_date) {
            if ($dateStart && strtotime($dateStart) > time()) {
                $the_date = strtotime($dateStart);
            } else {
                $the_date = strtotime($dateCreate);
            }
            $day = date('d', $the_date);
            $month = date('m', strtotime('15' . date('.m.Y', $the_date) . ' +1 year',));
            $year = date('Y', strtotime('+1 year', $the_date));
        } else {
            $day = date('d', $the_date);
            $month = date('m', $the_date);
            $year = date('Y', $the_date);
        }

        if (!checkdate(intval($month), intval($day), intval($year))) {
            $nextRepeatDate = date('28.02.Y', strtotime( "+1 year"));
        } else {
            $nextRepeatDate = date('d.m.Y', strtotime("+1 year", $the_date));
        }
        if (strtotime($nextRepeatDate) <= time()) {
            $the_date = strtotime($nextRepeatDate);
            return $this->getNextRepeatDatePlusYear($dateCreate, $dateStart, $the_date);
        }
        return $nextRepeatDate;
    }

    private function getNextRepeatDatePlusQuarter($dateCreate, $dateStart, $the_date=null) {
        if (!$the_date) {
            if ($dateStart && strtotime($dateStart) > time()) {
                $the_date = strtotime($dateStart);
            } else {
                $the_date = strtotime($dateCreate);
            }
            $day = date('d', $the_date);
            $month = date('m', strtotime('15' . date('.m.Y', $the_date) . ' +3 month'));
            $year = date('Y', strtotime('+3 month', $the_date));
        } else {
            $day = date('d', $the_date);
            $month = date('m', $the_date);
            $year = date('Y', $the_date);
        }

        if (!checkdate(intval($month), intval($day), intval($year))) {
            $nextRepeatDate = date('d.m.Y', strtotime("last day of next month", strtotime('+2 month', $the_date)));
        } else {
            $nextRepeatDate = date('d.m.Y', strtotime("+3 month", $the_date));
        }
        if (strtotime($nextRepeatDate) <= time()) {
            $the_date = strtotime($nextRepeatDate);
            return $this->getNextRepeatDatePlusYear($dateCreate, $dateStart, $the_date);
        }
        return $nextRepeatDate;
    }

    private function getNextRepeatDatePlusWeek($dateCreate, $dateStart, $the_date=null) {
        if (!$the_date) {
            if ($dateStart && strtotime($dateStart) > time()) {
                $the_date = strtotime($dateStart);
            } else {
                $the_date = strtotime($dateCreate);
            }
        }
        $nextRepeatDate = date('d.m.Y', strtotime("+1 week", $the_date));
        if (strtotime($nextRepeatDate) <= time()) {
            $the_date = strtotime($nextRepeatDate);
            return $this->getNextRepeatDatePlusYear($dateCreate, $dateStart, $the_date);
        }
        return $nextRepeatDate;
    }

    public function getAllRepeatedTasks() {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'deleted' => 0,
//                'type_id' => 1,
//                'deleted' => 0,
            ])
            ->andWhere(['not', ['repeat_type_id' => null]])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();

        foreach ($tasks as $task) {
            $task->nextRepeatDate = $this->getNextRepeatDate( $task);
        }

        return $tasks;
    }

    public function getNextRepeatDate(Tasks $task) {
        $dateCreate = date('d.m.Y', strtotime($task->date_create));
        if (!$task->repeat_type_id) {
            return false;
        }
        $today = date('Y-m-d');
        if ($task->repeat_start) {
            $dateStart = $task->repeat_start;
        } else {
            $dateStart = date('Y-m-d', strtotime($task->date_create));
        }
        $dateEnd = $task->repeat_end;
        switch ($task->repeat_type_id) {
            case 1:
                if ($dateStart == $today) {
                    $res = date('d.m.Y', strtotime($dateStart . ' +1 day'));
                } elseif (strtotime($dateStart) < time()) {
                    $res = date('d.m.Y', strtotime(' +1 day'));
                } else {
                    $res = date('d.m.Y', strtotime($dateStart));
                }
                break;
            case 2:
                $res = $this->getNextRepeatDatePlusMonth($dateCreate, $dateStart);
                break;
            case 3:
                $res = $this->getNextRepeatDatePlusYear($dateCreate, $dateStart);
                break;
            case 4:
                $res = $this->getNextRepeatDatePlusQuarter($dateCreate, $dateStart);
                break;
            case 5:
                $res = $this->getNextRepeatDatePlusWeek($dateCreate, $dateStart);
                break;
            case 6:
                $res = date('d.m.Y', $this->getNextWorkday($dateStart));
                break;
            case 7:
                $res = date('d.m.Y', $this->getNextHoliday($dateStart));
                break;
            case 8:
                $res = false;
                $selectedRepeats = explode(',', $task->repeated_weekdays);
                for ($i = 0; $i < count($selectedRepeats); $i++) {
                    $selectedRepeats[$i] = $selectedRepeats[$i] == 7 ? 0 : $selectedRepeats[$i];
                }

                $nextDays = array(time(), strtotime('+1 day'), strtotime('+2 days'), strtotime('+3 days'), strtotime('+4 days'), strtotime('+5 days'), strtotime('+6 days'), strtotime('+7 days'));
                for ($i = 0; $i < count($nextDays); $i++) {
                    $dayNum = (int) date('w', $nextDays[$i]);
//                    $daytext = date('d.m.Y', $nextDays[$i]);
                    if ((in_array($dayNum, $selectedRepeats))) {
                        $res = date('d.m.Y', $nextDays[$i]);
                        break;
                    }
                }
                break;
        }
        if (strtotime($res) >= strtotime($dateEnd) && $dateEnd) {
            $res = false;
        }
        return $res;
    }

    public function sendReportsToCurators() {
        $today = date('d.m.Y');
        $dayOfWeek = date('w', time());
        $yesterday = date('d.m.Y', strtotime("-1 day"));
        $lastStartWeekDay = date('d.m.Y', strtotime("-7 day"));

        $users = User::find()
            ->where([
                'mentor_email_confirm' => 1,
//                'finished' => 0,
            ])
            ->andWhere(['not', ['mentor_email' => null]])
            ->all();
        $reportsToSend = [];

        foreach ($users as $user) {
            // отправка ежедневно
            if ($user->mentor_email_repeat == 1) {
                $tasks = $this->getTasksByDateAndUserId($user->id, $yesterday);
                $userReports =[
                    'type' => 1,
                    'email' => $user->mentor_email,
                    'userName' => $user->name,
                    'userSurname' => $user->surname,
                    'userId' => $user->id,
                    'period' => 1,
                    'date1' => $yesterday,
                    'date2' => $yesterday,
                    'token' => $user->grade_token,
                    'reports' => [
                        ['date' => $yesterday,
                        'tasks' => $tasks,]
                    ],
                ];
            }
            // отправка раз в неделю
//            if ($user->mentor_email_repeat == 5) {
            if ($user->mentor_email_repeat == 5 && $dayOfWeek == 1) {
                $userReports =[
                    'type' => 5,
                    'email' => $user->mentor_email,
                    'userName' => $user->name,
                    'userSurname' => $user->surname,
                    'userId' => $user->id,
                    'period' => 5,
                    'date1' => $lastStartWeekDay,
                    'date2' => $yesterday,
                    'token' => $user->grade_token,
                    'reports' => [],
                ];
                $lastWeekDays = [strtotime('-1 day'), strtotime('-2 days'), strtotime('-3 days'), strtotime('-4 days'), strtotime('-5 days'), strtotime('-6 days'), strtotime('-7 days')];
                foreach ($lastWeekDays as $lastWeekDay) {
                    $dateFact = date('d.m.Y', $lastWeekDay);
                    $tasksByDate = $this->getTasksByDateAndUserId($user->id, $dateFact);
                    array_push($userReports['reports'], [
                        'date' => $dateFact,
                        'tasks' => $tasksByDate,
                    ]);
                }
            }
            if ($userReports) {
                array_push($reportsToSend, $userReports);
            }

        }

        $sendResult = true;
        foreach ($reportsToSend as $sendingReport) {
            $type = $sendingReport['type'] == 1 ? 'Ежедневный отчет' : 'Еженедельный отчет';
            $message = \Yii::$app->mailer->compose('mentors_report',[
                'email' => $sendingReport['email'],
                'name' => $sendingReport['userName'],
                'surname' => $sendingReport['userSurname'],
                'reports' => $sendingReport['reports'],
                'userId' => $sendingReport['userId'],
                'period' => $sendingReport['period'],
                'date1' => $sendingReport['date1'],
                'date2' => $sendingReport['date2'],
                'token' => $sendingReport['token'],
            ])
                ->setFrom('hello@iselfmade.ru')
                ->setTo($user->mentor_email)
                ->setSubject($sendingReport['userName'] . ' - ' . $type)
                ->send();
            if (!$message) {
                $sendResult = false;
            }
        }

        return $sendResult;
    }

    public function getTasksByDateAndUserId($userId, $date) {
        // преобразование даты в формат БД
        $d = \DateTime::createFromFormat('Y-m-d', $date);
        if ($d && $d->format('Y-m-d') === $date) {
            $formatDate = $date;
        } else {
            $formatDate = (new \DateTime($date))->format('Y-m-d');
        }

        $tasks = Tasks::find()
            ->where([
                'user_id' => $userId,
                'deleted' => 0,
//                'finished' => 0,
            ])
            ->andWhere(['AND',
                ['>=', 'date_calculate', $formatDate],
                ['<=', 'date_calculate', $formatDate . ' 23:59:59']
            ])
            ->andWhere(['AND',
                ['>=', 'date_start', $formatDate  . ' 00:00:00'],
                ['<=', 'date_start', $formatDate . ' 23:59:59']
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();

        return $tasks;
    }

    public function getUserTasksBetweenTwoDates($userId, $date1, $date2) {
        $tasks = Tasks::find()
            ->where([
                'user_id' => $userId,
                'deleted' => 0,
//                'finished' => 0,
            ])
//            ->andWhere(['AND',
//                ['>=', 'date_calculate', (new \DateTime(date($date1)))->format('Y-m-d H:i:s')],
//                ['<=', 'date_calculate', (new \DateTime($date2 . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
            ->andWhere(['AND',
                ['>=', 'date_start', (new \DateTime($date1  . ' 00:00:00'))->format('Y-m-d H:i:s')],
                ['<=', 'date_start', (new \DateTime($date2 . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();

        return $tasks;
    }

    public function getUserTasksByTypeIdBetweenTwoDates($userId, $date1, $date2, $typeId) {
        $tasks = Tasks::find()
            ->where([
                'user_id' => $userId,
                'deleted' => 0,
                'type_id' => $typeId,
            ])
            ->andWhere(['AND',
                ['>=', 'date_start', (new \DateTime($date1  . ' 00:00:00'))->format('Y-m-d H:i:s')],
                ['<=', 'date_start', (new \DateTime($date2 . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();

        return $tasks;
    }

    public function getArchiveTasksByDate($date) {
        $tasks = Tasks::find()
            ->where([
                'user_id' => \Yii::$app->user->getId(),
                'deleted' => 0,
            ])
//            ->andWhere(['AND',
//                ['>=', 'date_calculate', (new \DateTime(date($date)))->format('Y-m-d 00:00:00')],
//                ['<=', 'date_calculate', (new \DateTime($date . ' 23:59:59'))->format('Y-m-d H:i:s')]
//            ])
            ->andWhere(['AND',
                ['>=', 'date_start', (new \DateTime($date  . ' 00:00:00'))->format('Y-m-d H:i:s')],
                ['<=', 'date_start', (new \DateTime($date . ' 23:59:59'))->format('Y-m-d H:i:s')]
            ])
            ->orderBy(['date_create' => SORT_ASC])
            ->all();
        if ($tasks) {
            return $tasks;
        } else {
            return false;
        }

    }

    public function setUserGrades($userId, $period, $date1, $date2, $grade):bool {
        $today = date('Y-m-d');
        $dateStart = (new \DateTime(date($date1)))->format('Y-m-d');
        $dateEnd = (new \DateTime(date($date2)))->format('Y-m-d');
        $minDate = date('Y-m-d', strtotime("-7 day"));

        if ($dateStart < $minDate || $dateStart >= $today) {
            return false;
        }

        switch ($period) {
            case 1:
                $userGrade = UsersReports::findOne(['user_id' => $userId, 'date' => $dateStart]);
                if ($userGrade) {
                    if (!$userGrade->mentor_grade) {
                        $userGrade->mentor_grade = $grade;
                    } else {
                        return false;
                    }
                    if ($userGrade->save()) {
                        return true;
                    } else {
                        return false;
                    }
                } else {
                    if ($this->getTasksByDateAndUserId($userId, $dateStart)) {
                        $userGrade = new UsersReports();
                        $userGrade->user_id = $userId;
                        $userGrade->mentor_grade = $grade;
                        $userGrade->date = $dateStart;
                        if ($userGrade->save()) {
                            return true;
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                }
                break;
            case 5:
                $res = false;
                for ($i = 0; $i <= 6; $i++) {
                    if ($i == 0) {
                        $dateCur = (new \DateTime(date($date1)))->format('Y-m-d');
                    } else {
                        $dateCur = date('Y-m-d', strtotime($date1 . '+' . $i . ' day'));
                    }
                    $userGrade = UsersReports::findOne(['user_id' => $userId, 'date' => $dateCur]);
                    if ($userGrade) {
                        if (!$userGrade->mentor_grade) {
                            $userGrade->mentor_grade = $grade;
                            if ($userGrade->save()) {
                                $res = true;
                            }
                        }
                    } else {
                        if ($this->getTasksByDateAndUserId($userId, $dateCur)) {
                            $userGrade = new UsersReports();
                            $userGrade->user_id = $userId;
                            $userGrade->mentor_grade = $grade;
                            $userGrade->date = $dateCur;
                            if ($userGrade->save()) {
                                $res = true;
                            }
                        }
                    }
                }
                return $res;
                break;
            default:
                return false;
        }
    }

    public function getMonthsTasks($month, $year) {
        $compReports = \Yii::createObject(['class' => ReportsComponent::class,'modelClass' => UsersReports::class]);

        $userId = \Yii::$app->user->getId();
        $monthNumb = $month < 9 ? '0' . ($month + 1) : ($month + 1);
        $date1 = '01.' . $monthNumb . '.' . $year;
        $lastNumb = date('t', $date1);
        $date2 = $lastNumb . '.' . $monthNumb . '.' . $year;

        $tasksData = [];
        $dates = [];
        $datesStart = [];

        // получаем задачи за месяц
        $tasksInMonth = $this->getUserTasksByTypeIdBetweenTwoDates($userId, $date1, $date2, 1);
        // создаем массив дат старта этих задач
        foreach ($tasksInMonth as $task) {
            array_push($datesStart, \Yii::$app->formatter->asDateTime($task->date_start, 'php:Y-m-d'));
        }
        // отбираем только уникальные даты
        $dates = array_unique($datesStart);
        // получаем массив уникальных чисел в месяце с задачами
        foreach ($dates as $date) {
            array_push($tasksData, \Yii::$app->formatter->asDateTime($date, 'php:d'));
        }
        // получаем массив с числами месяца с отчетами иих статусами
        $reports = $compReports->getUserReportsByDatesArr($dates);
        // преобразуем в объект формата: число => статус
        $reportsData = [];
        foreach ($reports as $report) {
            $report->date = \Yii::$app->formatter->asDateTime($report->date, 'php:d');
            $reportsData[$report->date] = $report->status;
        }


        return [
            'reports' => $reportsData,
            'tasks' => $tasksData,
        ];
    }

    public function getCountsTasksForReports($reports) {
        $userId = \Yii::$app->user->getId();
        $current = 0;
        $finishedCount = 0;
        $tasks = [];
        foreach ($reports as $report) {
            $finishedCount = 0;
            $current = $this->getTasksByDateAndUserId($userId, $report->date);
            foreach ($current as $task) {
                if ($task->finished == 1) {
                    $finishedCount++;
                }
            }
            $tasks[$report->date] = [
                'tasks' => $current,
                'finishedCount' => $finishedCount,
                'totalCount' => count($current),
            ];
        }
        return $tasks;
    }

}