<?php


namespace app\models;


class ReportComments extends ReportCommentsBase {

    public $uploadFiles;

    public function beforeValidate() {

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function rules() {

        return array_merge([
            [['comment'], 'string', 'min' => 1],
            [['uploadFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => ['png', 'jpg', 'jpeg'], 'maxFiles' => 5, 'maxSize' => 1024 * 1024 * 2, 'tooBig'=> 'Максимальный размер файла 2MB'],
        ],parent::rules()); // TODO: Change the autogenerated stub
    }

    public function afterFind() {
        // ИСПРАВЛЕНИЕ ВРЕМЕНИ КОММЕНТАРИЯ, КОГДА В БАЗЕ СТОИТ ЧАСОВОЙ ПОЯС +3
        $this->date_create = date('Y-m-d H:i:s', strtotime($this->date_create)-3*60*60);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


    public function getUser() {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function getReportr() {
        return $this->hasOne(UsersReports::class, ['id' => 'report_id']);
    }

    public function attributeLabels() {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub
//        $labels['date_calculate'] = \Yii::t('app', 'Завершить:');
        return $labels;
    }

}